version: "3.8"

services:
  # 🐘 Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - "2181:2181" # ✅ standard port
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  # 🔄 Kafka broker
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # ✅ match ZK port
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network # ✅ add to network

  # 🚀 Go backend
  go-backend:
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: ncs-go
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    networks:
      - app-network

  # 🟦 Node.js backend
  node-backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./node/.env
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
