// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEscrow = "escrows"

// Escrow mapped from table <escrows>
type Escrow struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	JobID     int64     `gorm:"column:job_id;not null" json:"job_id"`
	ClientID  int64     `gorm:"column:client_id;not null" json:"client_id"`
	WorkerID  int64     `gorm:"column:worker_id;not null" json:"worker_id"`
	Amount    float64   `gorm:"column:amount;not null" json:"amount"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
}

// TableName Escrow's table name
func (*Escrow) TableName() string {
	return TableNameEscrow
}
