// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLobbyParticipant = "LobbyParticipant"

// LobbyParticipant mapped from table <LobbyParticipant>
type LobbyParticipant struct {
	ServiceRequestID int32     `gorm:"column:serviceRequestId;primaryKey" json:"serviceRequestId"`
	WorkerID         int32     `gorm:"column:workerId;primaryKey" json:"workerId"`
	Source           string    `gorm:"column:source;not null" json:"source"`
	Bid              float64   `gorm:"column:bid;not null" json:"bid"`
	Status           string    `gorm:"column:status;not null;default:pending" json:"status"`
	CreatedAt        time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
}

// TableName LobbyParticipant's table name
func (*LobbyParticipant) TableName() string {
	return TableNameLobbyParticipant
}
