// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotification = "Notification"

// Notification mapped from table <Notification>
type Notification struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int32     `gorm:"column:userId;not null" json:"userId"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	Messages  string    `gorm:"column:messages;not null" json:"messages"`
	Link      string    `gorm:"column:link" json:"link"`
	Read      bool      `gorm:"column:read;not null" json:"read"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
