// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceRequestLocation = "ServiceRequestLocation"

// ServiceRequestLocation mapped from table <ServiceRequestLocation>
type ServiceRequestLocation struct {
	ID               int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServiceRequestID int32   `gorm:"column:serviceRequestId;not null" json:"serviceRequestId"`
	Latitude         float64 `gorm:"column:latitude;not null" json:"latitude"`
	Longitude        float64 `gorm:"column:longitude;not null" json:"longitude"`
}

// TableName ServiceRequestLocation's table name
func (*ServiceRequestLocation) TableName() string {
	return TableNameServiceRequestLocation
}
