// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceRequestImage = "ServiceRequestImage"

// ServiceRequestImage mapped from table <ServiceRequestImage>
type ServiceRequestImage struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServiceRequestID int32  `gorm:"column:serviceRequestId;not null" json:"serviceRequestId"`
	URL              string `gorm:"column:url;not null" json:"url"`
}

// TableName ServiceRequestImage's table name
func (*ServiceRequestImage) TableName() string {
	return TableNameServiceRequestImage
}
