// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameServiceRequest = "ServiceRequest"

// ServiceRequest mapped from table <ServiceRequest>
type ServiceRequest struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ClientID    int32     `gorm:"column:clientId;not null" json:"clientId"`
	Category    string    `gorm:"column:category;not null" json:"category"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Budget      float64   `gorm:"column:budget;not null" json:"budget"`
	Urgency     string    `gorm:"column:urgency;not null" json:"urgency"`
	Status      string    `gorm:"column:status;not null;default:open" json:"status"`
	CreatedAt   time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	Latitude    float64   `gorm:"column:latitude;not null" json:"latitude"`
	Longitude   float64   `gorm:"column:longitude;not null" json:"longitude"`
}

// TableName ServiceRequest's table name
func (*ServiceRequest) TableName() string {
	return TableNameServiceRequest
}
