// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	EscrowID  int64     `gorm:"column:escrow_id;not null" json:"escrow_id"`
	Type      string    `gorm:"column:type;not null" json:"type"`
	Amount    float64   `gorm:"column:amount;not null" json:"amount"`
	Status    string    `gorm:"column:status;default:pending" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
