// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "Users"

// User mapped from table <Users>
type User struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Role      string    `gorm:"column:role;not null" json:"role"`
	Phone     string    `gorm:"column:phone;not null" json:"phone"`
	Wilaya    string    `gorm:"column:wilaya;not null" json:"wilaya"`
	Baladia   string    `gorm:"column:baladia;not null" json:"baladia"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
