// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorker = "Worker"

// Worker mapped from table <Worker>
type Worker struct {
	ID                  int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID              int32     `gorm:"column:userId;not null" json:"userId"`
	Availability        string    `gorm:"column:availability;not null" json:"availability"`
	Rating              float64   `gorm:"column:rating;not null" json:"rating"`
	CompletedJobs       int32     `gorm:"column:completedJobs;not null" json:"completedJobs"`
	Genre               string    `gorm:"column:genre;not null" json:"genre"`
	Bio                 string    `gorm:"column:bio" json:"bio"`
	Picture             string    `gorm:"column:picture" json:"picture"`
	NationalIDPicture   string    `gorm:"column:nationalIDPicture" json:"nationalIDPicture"`
	BusinessDocumentPDF string    `gorm:"column:businessDocumentPDF" json:"businessDocumentPDF"`
	Verified            bool      `gorm:"column:verified;not null" json:"verified"`
	CreatedAt           time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
}

// TableName Worker's table name
func (*Worker) TableName() string {
	return TableNameWorker
}
